### ISSUE TITLE
CPLEX Default Time Limit of 10 minutes

### ISSUE THREAD

**Issue by nicolas-kuechler** [spectrumauctions/sats-opt#11]
If you use the XOR Winner Determination in a big auction. (eg. LSVM Standard Configuration with all 6 * 2^16 bids), then it is possible that the winner determination reports missleading results.

CPLEX has by default a time limit of 10 minutes. Whenever it wasn't possible to find the optimal solution within 10 minutes, CPLEX just reports the best feasible solution it found so far. Because this happens without a notifcation, a user could assume that this is the optimal solution even though it is not.

In my opinion the user should have the opportunity to increase this time limit and if the winner determination truly stops because of this time limit then there should be an exception by default. 
Because I cannot really see the use case where a user would like to continue with a suboptimal solution in a winner determination problem.

With the following solve param, the default time limit of 600 seconds can be changed:

`mip.setSolveParam(SolveParam.TIME_LIMIT, 7200.0);`

**Comment by MiWeiss** [comment]
Thanks Nicolas for posting this issue. This is in fact a known issue but you're definitely right that we may want to throw an exception if the MIP solver hits the timeout.
IMO, the cleanest version to fix this issue would be to include the creation and throwing of the TimeoutException directly in jOPT (https://github.com/blubin/JOpt) and then pass it through in SATS-Opt to the SATS user. What do you think @Clabfabs ?

**Comment by islerfab** [comment]
I agree. If this is handled in JOpt, we can at least handle it, knowing that it's a suboptimal solution.
However, I suggest two improvements:
* Have a wrapper method in our sats-opt mips to set the time limit, and have a larger default time limit
* Have a flag that the user can set to define whether he's ok with almost-optimal solutions. Depending on the flag, either an exception is thrown in sats-opt or the suboptimal solution is presented anyway (this can still be useful in many cases).

What do you think?

**Comment by MiWeiss** [comment]
I fully agree. This I pretty much the solution I had in mind, too. Are you gonna discuss this with @blubin?

**Comment by blubin** [comment]
I am fine with adding a flag to JOpt that would cause it to throw an exception on timeout instead of simply reporting the result.  I'm not sure about changing the default behavior in JOpt, but clearly, even if we didn't the flag could be set by the default code in SATS-opt, (with its own option to accept approximate solutions -- and to change the timeout -- as you suggest).

**Comment by MiWeiss** [comment]
Awesome. I wouldn't change the default behavior in jOPT either, but make it configurable.
